// Auto-generated by generate_cpu_script_manifest.py; do not edit manually.
`ifndef CPU_SCRIPT_MANIFEST_SVH
`define CPU_SCRIPT_MANIFEST_SVH

`include "cpu_scripts/decimal.svh"
`include "cpu_scripts/extensive.svh"
`include "cpu_scripts/nominal.svh"
`include "cpu_scripts/sum_mul.svh"

`define CPU_SCRIPT_NAMES "decimal, extensive, nominal, sum_mul"

`define CPU_SCRIPT_CASES(iv,io,ifmt,s0,s1,s2,tid,req_ready,resp_valid,resp_tid,resp_data,resp_flags) \
case (cpu_script_sel) \
  "decimal": run_cpu_decimal(iv,io,ifmt,s0,s1,s2,tid,req_ready,resp_valid,resp_tid,resp_data,resp_flags); \
  "extensive": run_cpu_extensive(iv,io,ifmt,s0,s1,s2,tid,req_ready,resp_valid,resp_tid,resp_data,resp_flags); \
  "nominal": run_cpu_nominal(iv,io,ifmt,s0,s1,s2,tid,req_ready,resp_valid,resp_tid,resp_data,resp_flags); \
  "sum_mul": run_cpu_sum_mul(iv,io,ifmt,s0,s1,s2,tid,req_ready,resp_valid,resp_tid,resp_data,resp_flags); \
  default: begin \
    $display("ERROR: Unknown cpu_script '%s'. Available scripts: %s", cpu_script_sel, `CPU_SCRIPT_NAMES); \
    $finish; \
  end \
endcase

`endif
