import pathlib


def main() -> None:
    repo_root = pathlib.Path(__file__).resolve().parent
    cpu_dir = repo_root / "cpu_scripts"
    manifest = cpu_dir / "script_manifest.svh"

    scripts = sorted(p for p in cpu_dir.glob("*.svh") if p.name != manifest.name)
    lines = []
    lines.append("// Auto-generated by generate_cpu_script_manifest.py; do not edit manually.")
    lines.append("`ifndef CPU_SCRIPT_MANIFEST_SVH")
    lines.append("`define CPU_SCRIPT_MANIFEST_SVH")
    lines.append("")
    for script in scripts:
        lines.append(f'`include "cpu_scripts/{script.name}"')
    lines.append("")
    names = ", ".join(script.stem for script in scripts)
    lines.append(f'`define CPU_SCRIPT_NAMES "{names}"')
    lines.append("")
    lines.append("`define CPU_SCRIPT_CASES(iv,io,ifmt,s0,s1,s2,tid,req_ready,resp_valid,resp_tid,resp_data,resp_flags) \\\ncase (cpu_script_sel) \\")
    for script in scripts:
        stem = script.stem
        lines.append(f'  "{stem}": run_cpu_{stem}(iv,io,ifmt,s0,s1,s2,tid,req_ready,resp_valid,resp_tid,resp_data,resp_flags); \\')
    lines.append('  default: begin \\\n    $display("ERROR: Unknown cpu_script \'%s\'. Available scripts: %s", cpu_script_sel, `CPU_SCRIPT_NAMES); \\\n    $finish; \\\n  end \\\nendcase')
    lines.append("")
    lines.append("`endif")
    lines.append("")

    manifest.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
